"""Made changes to the models and routes(patch code)

Revision ID: d10b0e54f462
Revises: 119f19961263
Create Date: 2024-09-11 22:23:06.634643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10b0e54f462'
down_revision = '119f19961263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_records', schema=None) as batch_op:
        batch_op.alter_column('return_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_records', schema=None) as batch_op:
        batch_op.alter_column('return_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
